# Generated by Django 2.0.5 on 2018-06-26 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evnt_det', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='end_time',
            new_name='endtime',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='start_time',
            new_name='starttime',
        ),
    ]
