# Generated by Django 2.0.5 on 2018-06-26 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evnt_det', '0002_auto_20180626_1820'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='description',
            new_name='event_description',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='endtime',
            new_name='event_endtime',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='name',
            new_name='event_name',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='starttime',
            new_name='event_starttime',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='venue',
            new_name='event_venue',
        ),
    ]
